service: trivia-text

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    ACCOUNT_SID: ${file(./config.json):ACCOUNT_SID}
    ACCOUNT_TOKEN: ${file(./config.json):ACCOUNT_TOKEN}
    FROM_NUMBER: ${file(./config.json):FROM_NUMBER}
    MONGODB_URI: ${file(./config.json):MONGODB_URI}
    QUESTION_ID: ${file(./config.json):QUESTION_ID}

functions:
  sendQuestion:
    handler: sendQuestion.handler
    events:
      - schedule: cron(0 12 * * ? *)
  setQuestion:
    handler: setQuestion.handler
    events:
      - schedule: cron(0 11 * * ? *)
  webhook:
    handler: webhook.handler
    events:
      - http:
          method: POST
          path: webhook
          cors: true